--create table in do.create file
CREATE TABLE folders (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    folder_name TEXT NOT NULL,
)

CREATE TABLE notes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    note_name TEXT NOT NULL,
    date_modified TIMESTAMPTZ NOT NULL DEFAULT now(),
    content TEXT,
)

--alter notes table to add foreign key
ALTER TABLE notes
ADD COLUMN
    folder_id INTEGER 
        REFERENCES folders(id) ON DELETE CASCADE NOT NULL;
